// components/icons.tsx
import {
    Wrench,
    Home,
    Car,
    Trash2,
    Flower2,
    Zap,
    Droplet,
    Brush,
    Truck,
    ChevronLeft,
    ChevronRight,
    Plus,
    Minus,
    X,
    Check,
    Settings,
    User,
    Calendar,
    Gift,
    List,
    Lock,
    LogOut,
    Copy,
    Loader2,
    LucideProps,
    Link,
    Star,
    MapPin,
    Clock,
    CheckCircle,
    Users,
    IndianRupee
  } from "lucide-react"
  
  export const Icons = {
    Wrench: (props: LucideProps) => <Wrench {...props} />,
    Home: (props: LucideProps) => <Home {...props} />,
    Car: (props: LucideProps) => <Car {...props} />,
    Trash: (props: LucideProps) => <Trash2 {...props} />,
    Garden: (props: LucideProps) => <Flower2 {...props} />,
    Electric: (props: LucideProps) => <Zap {...props} />,
    Water: (props: LucideProps) => <Droplet {...props} />,
    Cleaning: (props: LucideProps) => <Brush {...props} />,
    Moving: (props: LucideProps) => <Truck {...props} />,
    ChevronLeft: (props: LucideProps) => <ChevronLeft {...props} />,
    ChevronRight: (props: LucideProps) => <ChevronRight {...props} />,
    Plus: (props: LucideProps) => <Plus {...props} />,
    Minus: (props: LucideProps) => <Minus {...props} />,
    X: (props: LucideProps) => <X {...props} />,
    Check: (props: LucideProps) => <Check {...props} />,
    Settings: (props: LucideProps) => <Settings {...props} />,
    User: (props: LucideProps) => <User {...props} />,
    Calendar: (props: LucideProps) => <Calendar {...props} />,
    Gift: (props: LucideProps) => <Gift {...props} />,
    List: (props: LucideProps) => <List {...props} />,
    Lock: (props: LucideProps) => <Lock {...props} />,
    LogOut: (props: LucideProps) => <LogOut {...props} />,
    Copy: (props: LucideProps) => <Copy {...props} />,
    Loader2: (props: LucideProps) => <Loader2 {...props} />,
    Link: (props: LucideProps) => <Link {...props} />,
    Star: (props: LucideProps) => <Star {...props} />,
    MapPin: (props: LucideProps) => <MapPin {...props} />,
    Clock: (props: LucideProps) => <Clock {...props} />,
    CheckCircle: (props: LucideProps) => <CheckCircle {...props} />,
    Users: (props: LucideProps) => <Users {...props} />,
    IndianRupee: (props: LucideProps) => <IndianRupee {...props} />
  }