// components/icons.tsx
import {
    Wrench,
    Home,
    Car,
    Trash2,
    Flower2,
    Zap,
    Droplet,
    Brush,
    Truck,
    ChevronLeft,
    ChevronRight,
    Plus,
    Minus,
    X,
    Check,
    Settings,
    User,
    Calendar,
    LucideProps,
  } from "lucide-react"
  
  export const Icons = {
    Wrench: (props: LucideProps) => <Wrench {...props} />,
    Home: (props: LucideProps) => <Home {...props} />,
    Car: (props: LucideProps) => <Car {...props} />,
    Trash: (props: LucideProps) => <Trash2 {...props} />,
    Garden: (props: LucideProps) => <Flower2 {...props} />,
    Electric: (props: LucideProps) => <Zap {...props} />,
    Water: (props: LucideProps) => <Droplet {...props} />,
    Cleaning: (props: LucideProps) => <Brush {...props} />,
    Moving: (props: LucideProps) => <Truck {...props} />,
    ChevronLeft: (props: LucideProps) => <ChevronLeft {...props} />,
    ChevronRight: (props: LucideProps) => <ChevronRight {...props} />,
    Plus: (props: LucideProps) => <Plus {...props} />,
    Minus: (props: LucideProps) => <Minus {...props} />,
    X: (props: LucideProps) => <X {...props} />,
    Check: (props: LucideProps) => <Check {...props} />,
    Settings: (props: LucideProps) => <Settings {...props} />,
    User: (props: LucideProps) => <User {...props} />,
    Calendar: (props: LucideProps) => <Calendar {...props} />,
  }